### PR TITLE
Fix setloop

### PR DESCRIPTION
**Pull request by ThePerfectLuigi64**

### CODE REVIEW

**Review by KazeEmanuar — COMMENTED** [review]
What does this change?

**Comment by ThePerfectLuigi64** [comment]
> What does this change?

This allows the file to run.

**Comment by ThePerfectLuigi64** [comment]
since the old one wasn't able to run unless you post processed it.

**Comment by KazeEmanuar** [comment]
it worked on my machine   ™
i'm sure this has to be compiled for every machine individually then and
this edited file will provide the same value to other users as the original
file did

Am Di., 11. Juni 2024 um 23:17 Uhr schrieb ThePerfectLuigi64 <
***@***.***>:

**Pull request merged**
